// <auto-generated />
using System;
using MauiApp2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MauiApp2.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250910134748_AutoMigration_20250910_104730")]
    partial class AutoMigration_20250910_104730
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("MauiApp2.ClassManaging.ComponentApplicationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentGradeComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentGradeComponentId");

                    b.ToTable("ComponentApplicationInfo");
                });

            modelBuilder.Entity("MauiApp2.ClassManaging.GradingComponentBinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classroom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GradingComponentBinders");
                });

            modelBuilder.Entity("MauiApp2.ClassManaging.StudentGradeComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCourses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("MauiApp2.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MauiApp2.ClassManaging.ComponentApplicationInfo", b =>
                {
                    b.HasOne("MauiApp2.ClassManaging.StudentGradeComponent", null)
                        .WithMany("AvailableInfo")
                        .HasForeignKey("StudentGradeComponentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MauiApp2.ClassManaging.GradingComponentBinder", b =>
                {
                    b.HasOne("MauiApp2.Data.User", "User")
                        .WithMany("GradingComponents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MauiApp2.ClassManaging.StudentGradeComponent", b =>
                {
                    b.Navigation("AvailableInfo");
                });

            modelBuilder.Entity("MauiApp2.Data.User", b =>
                {
                    b.Navigation("GradingComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
